[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "backend",
]

[tool.coverage.run]
source = [
    "gn_module_zh",
]
omit = [
    "*/tests/*",
    "*/migrations/*",
]

[tool.black]
line-length = 99